### ISSUE TITLE
现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗

### ISSUE THREAD

**Issue by lan2000** [leanflutter/flutter_superplayer#2]
目前已经有
_playerController.uiHideController();
_playerController.uiHideDanmu();
_playerController.uiHideReplay();
等单次隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击屏幕也不再显示原有菜单控件吗，
目的是除了播放器以外的其他UI都在flutter这边构建

**Comment by lijy91** [comment]
正在增加该功能，通过设置 controlViewType 来隐藏原生的控制视图
```dart
SuperPlayerView(
  controller: _playerController,
  controlViewType: kControlViewTypeWithout,
),
```

**Comment by lan2000** [comment]
嗯，我今天弄了一下，感觉可以把onPlayEvent返回的参数直接传给flutter，不需要原生这边进行处理。今天测试的时候发现加载错误直播地址，点击播放，播放器也不提示loading，就黑屏，等好一段时间提示错误并显示重新播放按钮。IOS那边没接触过，所以希望能flutter那边处理播放器事件。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 晚上10:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
正在增加该功能，通过设置 controlViewType 来隐藏原生的控制视图
 SuperPlayerView(   controller: _playerController,   controlViewType: kControlViewTypeWithout, ),

**Comment by lijy91** [comment]
@lan2000 现在也是可能通过 `SuperPlayerListener` 来监听这些事件的，今天也有考虑把 ControlView 直接用 Dart 来实现。

**Comment by lan2000** [comment]
在flutter里面实现全屏播放视频，好像有点问题。能实现类型video_player那种效果吗。
我看一些说明：
在 Android 原生层中 video_player 使用的是 exoplayer 播放内核，那么如上图所示，VideoPlayerController 会在初始化的时候通过 MethodChannel 和原生端通信，之后准备好播放内核和 Surface，最后将对应的 textureId 返回到 Dart 中。

所以在前面的代码中，需要在全屏和非全屏页面使用同一个 VideoPlayerController，这样它们就具备了同一个 textureId。

具备同一个 textureId 后，那么只要原生层不停止播放， textureId  对应的原生数据就一直处于更新状态，而这时候虽然跳转路由页面，但不同的 VideoPlayer 内部的 Texture 控件用的是同一个 VideoPlayerController，也就是同一个 textureId ，所以它们会呈现出通用的画面。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 晚上11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
@lan2000 现在也是可能通过 SuperPlayerListener 来监听这些事件的，今天也有考虑把 ControlView 直接用 Dart 来实现。

**Comment by lan2000** [comment]
运行在模拟器报错；
 Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/包名/base.apk"],nativeLibraryDirectories=[/data/app/包名/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"

**Comment by lan2000** [comment]
ndk加上x86就好了

**Comment by lijy91** [comment]
> ndk加上x86就好了

官方目前不支持 x86 https://github.com/tencentyun/SuperPlayer_Android/issues/133#issuecomment-755867131

**Comment by lan2000** [comment]
和flutter的trtc同时使用的话会冲突



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





  
ndk加上x86就好了
  
官方目前不支持 x86 tencentyun/SuperPlayer_Android#133 (comment)

**Comment by lan2000** [comment]
FAILURE: Build failed with an exception.


* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
&gt; 1 exception was raised by workers:
&nbsp; java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine$Stub found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine$Stub$Proxy found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature$Stub found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature$Stub$Proxy found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audiokit.config.ResultCode found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audiokit.config.Version found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audiokit.interfaces.AudioFeaturesKit found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
&nbsp; Duplicate class com.huawei.multimedia.liteav.audiokit.interfaces.FeatureKitManager found in modules jetified-LiteAVSDK_Professional-8.5.10028-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.5.10028) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)

.......




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 上午9:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





  
ndk加上x86就好了
  
官方目前不支持 x86 tencentyun/SuperPlayer_Android#133 (comment)

**Comment by lijy91** [comment]
> 和flutter的trtc同时使用的话会冲突
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月21日(星期三) 上午9:00 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2) ndk加上x86就好了 官方目前不支持 x86 [tencentyun/SuperPlayer_Android#133](https://github.com/tencentyun/SuperPlayer_Android/issues/133) (comment) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

需要将 repo fork 一份并使用同一版本的 LiteAVSDK。

**Comment by lan2000** [comment]
使用同一个版本

> 1 exception was raised by workers:
  java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine found in modules jetified-LiteAVSDK_Player-8.2.9808-runtime.jar (com.tencent.liteav:LiteAVSDK_Player:8.2.9808) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine$Stub found in modules jetified-LiteAVSDK_Player-8.2.9808-runtime.jar (com.tencent.liteav:LiteAVSDK_Player:8.2.9808) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)

**Comment by lan2000** [comment]
Execution failed for task ':app:checkDebugDuplicateClasses'.
> 1 exception was raised by workers:
  java.lang.RuntimeException: Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine$Stub found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioEngine$Stub$Proxy found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature$Stub found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audioengine.IHwAudioKaraokeFeature$Stub$Proxy found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)
  Duplicate class com.huawei.multimedia.liteav.audiokit.config.ResultCode found in modules jetified-LiteAVSDK_Professional-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_Professional:8.2.9809) and jetified-LiteAVSDK_TRTC-8.2.9809-runtime.jar (com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809)

**Comment by lijy91** [comment]
@lan2000 

修改 `android/build.gradle` 

```diff
group 'org.leanflutter.plugins.flutter_superplayer'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 19
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    android {
        compileOptions {
            sourceCompatibility 1.8
            targetCompatibility 1.8
        }
    }

    dependencies {
-        implementation 'com.tencent.liteav:LiteAVSDK_Professional:latest.release'
+        implementation 'com.tencent. liteav:LiteAVSDK_TRTC:latest.release' 
        implementation 'com.github.ctiao:DanmakuFlameMaster:0.5.4'
    }
}
```

**Comment by lan2000** [comment]
D:\flutter\xxx\flutter_superplayer\android\src\main\java\com\tencent\liteav\demo\play\SuperPlayerView.java:48: ����: �Ҳ�������
import com.tencent.rtmp.ITXVodPlayListener;
                       ^
  ����:   �� ITXVodPlayListener
  λ��: ����� com.tencent.rtmp
D:\flutter\xxx\flutter_superplayer\android\src\main\java\com\tencent\liteav\demo\play\SuperPlayerView.java:53: ����: �Ҳ�������
import com.tencent.rtmp.TXVodPlayConfig;
                       ^
  ����:   �� TXVodPlayConfig
  λ��: ����� com.tencent.rtmp
D:\flutter\xxx\flutter_superplayer\android\src\main\java\com\tencent\liteav\demo\play\SuperPlayerView.java:54: ����: �Ҳ�������
import com.tencent.rtmp.TXVodPlayer;
                       ^
  ����:   �� TXVodPlayer
  λ��: ����� com.tencent.rtmp

**Comment by lan2000** [comment]
LiteAVSDK_Professional比 LiteAVSDK_TRTC 全面，要把tencent_trtc_cloud里面的改为LiteAVSDK_Professional 就能通过编译

**Comment by lijy91** [comment]
> play

这几个文件应该已经被移除了，可以先清空一下缓存

**Comment by lan2000** [comment]
好的，我再试试

**Comment by lan2000** [comment]
![image](https://user-images.githubusercontent.com/29618907/115527153-60208b00-a2c3-11eb-90a2-3bdbae0e368a.png)

**Comment by lijy91** [comment]
看着像是用了 TRTC 版本的 SDK

**Comment by lijy91** [comment]
照理应该是没有 `android/src/main/java/com/tencent/liteav/demo/play` 这个目录了的

**Comment by lan2000** [comment]
我用不是最新版本







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
照理应该是没有 android/src/main/java/com/tencent/liteav/demo/play 这个目录了的

**Comment by lan2000** [comment]
你能把
提交： 7c6d6edff3165075c76cbe2003c909445fe25b19 [7c6d6ed]
父级： 64f2a0adbc
作者： LiJianying ***@***.***&gt;
日期： 2020年10月26日 16:25:12
提交者： LiJianying
[Android] Update from SuperPlayer_Android

这个日期的项目，把里面改成implementation 'com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809'
然后再发给我吗，ios那边我没接触过过




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
照理应该是没有 android/src/main/java/com/tencent/liteav/demo/play 这个目录了的

**Comment by lijy91** [comment]
> 你能把 提交： [7c6d6ed](https://github.com/leanflutter/flutter_superplayer/commit/7c6d6edff3165075c76cbe2003c909445fe25b19) [[7c6d6ed](https://github.com/leanflutter/flutter_superplayer/commit/7c6d6edff3165075c76cbe2003c909445fe25b19)] 父级： [64f2a0a](https://github.com/leanflutter/flutter_superplayer/commit/64f2a0adbcfd3557c45cc634d96d0463e796806d) 作者： LiJianying ***@***.***&gt; 日期： 2020年10月26日 16:25:12 提交者： LiJianying [Android] Update from SuperPlayer_Android 这个日期的项目，把里面改成implementation 'com.tencent.liteav:LiteAVSDK_TRTC:8.2.9809' 然后再发给我吗，ios那边我没接触过过
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月21日(星期三) 下午5:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2) 照理应该是没有 android/src/main/java/com/tencent/liteav/demo/play 这个目录了的 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

没理解你的意思，建议你更新到最新版本再修改这些

**Comment by lan2000** [comment]
新版本要升级sdk和支持空安全，我是想找个空余时间来弄的，打算到五一------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月21日(星期三) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)

**Comment by lijy91** [comment]
可以试着引用 `no-sound-null-safety` 分支

https://github.com/leanflutter/flutter_superplayer/tree/no-sound-null-safety

**Comment by lan2000** [comment]
好的，晚点再测，非常感谢。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月21日(星期三) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)

**Comment by lan2000** [comment]
我使用引用&nbsp;no-sound-null-safety&nbsp;分支。然后改为implementation 'com.tencent. liteav:LiteAVSDK_TRTC:latest.release' 






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
@lan2000
 
修改 android/build.gradle
 group 'org.leanflutter.plugins.flutter_superplayer' version '1.0' buildscript {     repositories {         google()         jcenter()     }     dependencies {         classpath 'com.android.tools.build:gradle:3.5.0'     } } rootProject.allprojects {     repositories {         google()         jcenter()     } } apply plugin: 'com.android.library' android {     compileSdkVersion 28     defaultConfig {         minSdkVersion 19     }     lintOptions {         disable 'InvalidPackage'     }     android {         compileOptions {             sourceCompatibility 1.8             targetCompatibility 1.8         }     }     dependencies { -        implementation 'com.tencent.liteav:LiteAVSDK_Professional:latest.release' +        implementation 'com.tencent. liteav:LiteAVSDK_TRTC:latest.release'          implementation 'com.github.ctiao:DanmakuFlameMaster:0.5.4'     } }

**Comment by lan2000** [comment]
我使用引用no-sound-null-safety;分支。然后改为implementation 'com.tencent. liteav:LiteAVSDK_TRTC:latest.release'


还是这个问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午4:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
@lan2000
 
修改 android/build.gradle
 group 'org.leanflutter.plugins.flutter_superplayer' version '1.0' buildscript {     repositories {         google()         jcenter()     }     dependencies {         classpath 'com.android.tools.build:gradle:3.5.0'     } } rootProject.allprojects {     repositories {         google()         jcenter()     } } apply plugin: 'com.android.library' android {     compileSdkVersion 28     defaultConfig {         minSdkVersion 19     }     lintOptions {         disable 'InvalidPackage'     }     android {         compileOptions {             sourceCompatibility 1.8             targetCompatibility 1.8         }     }     dependencies { -        implementation 'com.tencent.liteav:LiteAVSDK_Professional:latest.release' +        implementation 'com.tencent. liteav:LiteAVSDK_TRTC:latest.release'          implementation 'com.github.ctiao:DanmakuFlameMaster:0.5.4'     } }

**Comment by lan2000** [comment]
播放器进入页面，都没播放视频，获取当前播放状态就是显示当前正在播放



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
可以试着引用 no-sound-null-safety 分支
 
https://github.com/leanflutter/flutter_superplayer/tree/no-sound-null-safety

**Comment by lan2000** [comment]
原生播放器有也有一个问题，播放视频除了他给的loading状态，点击播放按钮之后，到真实缓冲和播放视频之间间隔时间很长，这个时候并没有loading的提示



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月21日(星期三) 下午5:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leanflutter/flutter_superplayer] 现在有隐藏播放器菜单功能，点击屏幕还能显示出来，可以让点击也不再显示原有菜单控件吗 (#2)





 
可以试着引用 no-sound-null-safety 分支
 
https://github.com/leanflutter/flutter_superplayer/tree/no-sound-null-safety
