### ISSUE TITLE
大佬，能解决下初始播放视频的时候，加一个loading显示吗

### ISSUE THREAD

**Issue by lan2000** [leanflutter/flutter_superplayer#3]
进入页面播放视频，网络情况一般的时候，加载视频需要几秒钟，但是这个时间内无任何loading 的提示

**Comment by lan2000** [comment]
还有一个就是可以加上调整音量大小和静音的API吗，万分感谢

**Comment by lijy91** [comment]
是 Android 还是 iOS 会出现这个问题呢？

**Comment by lan2000** [comment]
安卓这边的，我用的是no-sound-null-safety这个分支。
原生安卓的腾讯的这个播放器我之前试的时候也会有这个问题，很早很早以前是没有和这个问题。因为之前旧的版本进入页面加载视频直接显示loading，监听到播放视频才隐藏loading。现在腾讯改成监听到loading事件才显示loading······

**Comment by lan2000** [comment]
能添加静音/解除静音的功能吗

**Comment by lijy91** [comment]
由于这个 loading 状态是由 SDK 维护的，所以暂时不考虑做什么修改，为了效果好一些增加了设置封面的功能来优化一下体验。

```
_playerController.setCoverImage('http://xiaozhibo-10055601.file.myqcloud.com/coverImg.jpg');
```
