### ISSUE TITLE
大侠，能增加Android的setLoop循环播放选项吗？

### ISSUE THREAD

**Issue by patton88** [leanflutter/flutter_superplayer#5]
大侠，能增加Android的setLoop循环播放选项吗？或者怎样自己添加setLoop循环播放选项？先谢了！
比如：[https://github.com/arcticfox1919/ftxplayer.git](https://github.com/arcticfox1919/ftxplayer.git)

  Future<void> init() async {
    if (!mounted) return;
    _controller.onPlayerState.listen((val){
      debugPrint("********** $val **********");
    });
    // 开启调试日志
    await FTXPlayerController.setConsoleEnabled(true);
    // 初始化播放器
    await _controller.initialize(onlyAudio: true);
    // 设置循环播放
    await _controller.setLoop(true);
    // 开始播放
    await _controller.play("http://music.163.com/song/media/outer/url?id=436514312.mp3");
  }

**Comment by lijy91** [comment]
@patton88 已经添加 `setLoop` 方法，请更新到 `0.0.2` 。
```dart
_playerController.setLoop(true);
```

**Comment by patton88** [comment]
非常感谢！祝该组件越做越红火！
