### ISSUE TITLE
flutter_superplayer 0.0.2版本，下面build.gradle文件中的ndk需要注释掉，否则高版本arm64-v8a系列真机运行example闪退

### ISSUE THREAD

**Issue by patton88** [leanflutter/flutter_superplayer#6]
flutter_superplayer 0.0.2版本，下面build.gradle文件中的ndk需要注释掉，否则高版本arm64-v8a系列真机运行example闪退

flutter_superplayer0.0.2\example\android\app\build.gradle

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "org.leanflutter.plugins.flutter_superplayer_example"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        //ndk {
        //    abiFilters "armeabi-v7a"
        //}
    }

**Comment by lijy91** [comment]
已移除

**Comment by patton88** [comment]
多谢大侠及时修复！
