### ISSUE TITLE
模拟器运行编译不通过

### ISSUE THREAD

**Issue by alanfit** [leanflutter/flutter_superplayer#7]
ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

请问这个有解决办法没

**Comment by lijy91** [comment]
example 可以正常运行吗？

**Comment by lijy91** [comment]
需要把完整的错误信息发一下

**Comment by lijy91** [comment]
初步判断是由于 TXLiteAVSDK 升级导致的，临时解决方案先修改 `Podfile.lock` 由此固定 TXLiteAVSDK 的版本为 `8.6.10094`

根据以下修改

```
PODS:
  - TXLiteAVSDK_Professional (8.6.10094)

...

SPEC CHECKSUMS:
  TXLiteAVSDK_Professional: e8284aa1f25d61b18a8a7fe7e24ce0cf9d01fd33

...

COCOAPODS: 1.10.1
```
