### ISSUE TITLE
添加静音/解除静音功能

### ISSUE THREAD

**Issue by lijy91** [leanflutter/flutter_superplayer#8]
能添加静音/解除静音的功能吗

_Originally posted by @lan2000 in https://github.com/leanflutter/flutter_superplayer/issues/3#issuecomment-847659427_

**Comment by lan2000** [comment]
打开页面，如何监听SuperPlayerView已经完成初始化，可以播放视频？
达到效果是设置好视频url，显示页面就让播放器自动播放。

**Comment by lan2000** [comment]
3、播放器的PlayConfig配置什么时候可以支持

**Comment by lan2000** [comment]
4、现在报错的吐司都是固定且是中文。有一个建议，把播放器的onPlayEvent 通知到dart这边，用户可以选择是否自己处理。
