### ISSUE TITLE
使用pSign播放报错

### ISSUE THREAD

**Issue by ShawnHe1024** [leanflutter/flutter_superplayer#9]
大佬，能帮忙看一下嘛？
云点播视频开启防盗链检测后使用pSign传参报错：
![image](https://user-images.githubusercontent.com/25680420/128468611-d773d797-1f23-4be0-804d-cfa28bf8da4c.png)
签名在web端使用官方sdk播放正常

**Comment by lijy91** [comment]
麻烦加一下我的微信 `lijy91` 提供一下测试参数

**Comment by lijy91** [comment]
已修复不支持 pSign 参数的问题
